services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  back-ventas:
    image: ${DOCKERHUB_USERNAME}/back-ventas:latest
    container_name: back-ventas
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - backend

  back-despachos:
    image: ${DOCKERHUB_USERNAME}/back-despachos:latest
    container_name: back-despachos
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
